services:
  jwdj-backend:
    build:
      context: .
      target: backend
    environment:
      JWDJ_DATABASE_TYPE: sqlite3
    volumes:
      - ./db:/db
    expose:
      - 8000
    env_file:
      - .env

  jwdj-nginx:
    build:
      context: .
      target: nginx
    ports:
      - 1337:80
    depends_on:
      - jwdj-backend
