version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    command: sh -c "./manage.py migrate && gunicorn server.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./db:/db
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    build:
      context: .
      target: nginx
    ports:
      - 1337:80
    depends_on:
      - backend
