# Generated by Django 4.1.5 on 2023-01-16 22:10

from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("note", models.CharField(max_length=2048, null=True)),
                ("owner", models.CharField(max_length=32)),
                ("created", models.DateTimeField(auto_now=True)),
                ("votes", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("owner", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=2048)),
                ("allow_not_voted", models.BooleanField()),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "valid_until",
                    models.DateTimeField(default=server.models._default_valid_until),
                ),
                ("published", models.DateTimeField(default=None, null=True)),
                ("closed", models.DateTimeField(default=None, null=True)),
                ("closed_option_idx", models.SmallIntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=64)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.poll"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["valid_until"], name="server_poll_valid_u_899646_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["owner"], name="server_poll_owner_162e24_idx"),
        ),
        migrations.AddField(
            model_name="ballot",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="server.poll"
            ),
        ),
        migrations.AddIndex(
            model_name="ballot",
            index=models.Index(fields=["owner"], name="server_ball_owner_100092_idx"),
        ),
    ]
